user www;
error_log /var/log/nginx/error.log;
body_size 1 MB;

server {
    listen 127.0.0.1 8080;
    server_name 127.0.0.1:8080;
    error_page 404 504 418 error.html;
    error_page 500 test.html;
    error_page 404 error404.html;

    location /photos {
    root ./web; 
    index index.html;
    dirlisting on;
    methods GET;
    }

    location /farfadet {
    redirect 301 rickroll.com;
    }

    location /photos/chien {
    methods POST DELETE GET;
    index doggo.html;
    root /var/www/;
    upload_path /var/www/photos/uploads;
    }
}

server {
    listen 127.0.0.8 8080;
    server_name admin.ebesnoin.com admin.ebesnoin.fr;
    error_page 404 504 418 tomato.html;

    location /tet  {
    root /var/www/admin;
    index index.html;
    dirlisting off;
    methods GET POST;
    }

    location /friends/chat/ {
    index home.py;
    cgi_extension .py /usr/bin/python3;
    cgi_extension .php /usr/bin/php-cgi;
    root /var/www/chatting;
    }
}


# Available directives:
# -- in General:
#   - user "username";
#   - error_log "path";
#   - body_size "size in bytes" [KB | MB | GB];

# -- in Server:
#   - listen "ip" "port";
#   - server_name "domain" [domain, ...];
#   - error_page "code" [code, ...] "path";

# -- in Location:
#   - location "path" {
#   - root "path";
#   - index "file";
#   - dirlisting on|off;
#   - methods [GET &| POST &| DELETE];
#   - redirect "code" "url";
#   - cgi_extension ".ext" "path";
#   - upload_path "path";

# comments work, but only one line comments are supported.
# Comments must be on their own line, starting with a "#".
# Comments can be placed anywhere in the file.
# Invalid directives will throw and error and stop the parsing.

# Example of a configuration file: